name: RandomSpawnPlus
version: ${project.version}
main: systems.kscott.randomspawnplus3.RandomSpawnPlus
api-version: 1.13
authors: [89apt89]
description: A comprehensive random spawning plugin for modern Minecraft versions.
load: POSTWORLD