name: RandomSpawnPlus
version: ${project.version}
main: systems.kscott.randomspawnplus3.RandomSpawnPlus
api-version: 1.13
softdepend: [Essentials, Factions]
authors: [89apt89]
description: A comprehensive random spawning plugin for modern Minecraft versions.
load: POSTWORLD

commands:
  wild:
    description: Get a wild spawn
    usage: /wild [player]

permissions:
  randomspawnplus.randomspawn:
    description: Enable random spawns
  randomspawnplus.wild:
    description: Teleport to a random location
  randomspawnplus.wild.others:
    description: Teleport others to a random location
  randomspawnplus.wild.bypasscooldown:
    description: Bypass the teleport cooldown